# Redis configuration file
bind 0.0.0.0
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300
loglevel notice
databases 16

# Save the DB to disk
save 900 1
save 300 10
save 60 10000

rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data
maxmemory 512mb
maxmemory-policy noeviction
